
SUPABASE_URL = "https://uwyccbpcqxsacpshwrlh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eWNjYnBjcXhzYWNwc2h3cmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQzMjIzMjQsImV4cCI6MjAyOTg5ODMyNH0.IIoJA37ufJQ6Aii6dfwIG8ueD4tFkGcYdTtFPtlS29I"